-- Initial relationship types. Preserve existing administrator labels and active status.
BEGIN;
SELECT set_config('app.actor_type','automated_process',true),set_config('app.actor_name','Relationship catalogue seeding',true),set_config('app.event_source','seeding',true);
INSERT INTO relationship_types(resource_kind,code,forward_name,reverse_name,translations,is_symmetric) VALUES ('aggregation','related_to','related to','related to','{"ar": {"forward_name": "مرتبط بـ", "reverse_name": "مرتبط بـ"}}',true) ON CONFLICT(resource_kind,code) DO NOTHING;
INSERT INTO relationship_types(resource_kind,code,forward_name,reverse_name,translations,is_symmetric) VALUES ('aggregation','supersedes','supersedes','superseded by','{"ar": {"forward_name": "يحل محل", "reverse_name": "حل محله"}}',false) ON CONFLICT(resource_kind,code) DO NOTHING;
INSERT INTO relationship_types(resource_kind,code,forward_name,reverse_name,translations,is_symmetric) VALUES ('aggregation','continues','continues','continued by','{"ar": {"forward_name": "يستكمل", "reverse_name": "استكمله"}}',false) ON CONFLICT(resource_kind,code) DO NOTHING;
INSERT INTO relationship_types(resource_kind,code,forward_name,reverse_name,translations,is_symmetric) VALUES ('aggregation','references','references','referenced by','{"ar": {"forward_name": "يشير إلى", "reverse_name": "أشار إليه"}}',false) ON CONFLICT(resource_kind,code) DO NOTHING;
INSERT INTO relationship_types(resource_kind,code,forward_name,reverse_name,translations,is_symmetric) VALUES ('record','related_to','related to','related to','{"ar": {"forward_name": "مرتبط بـ", "reverse_name": "مرتبط بـ"}}',true) ON CONFLICT(resource_kind,code) DO NOTHING;
INSERT INTO relationship_types(resource_kind,code,forward_name,reverse_name,translations,is_symmetric) VALUES ('record','supersedes','supersedes','superseded by','{"ar": {"forward_name": "يحل محل", "reverse_name": "حل محله"}}',false) ON CONFLICT(resource_kind,code) DO NOTHING;
INSERT INTO relationship_types(resource_kind,code,forward_name,reverse_name,translations,is_symmetric) VALUES ('record','redaction_of','redaction of','redaction source of','{"ar": {"forward_name": "نسخة منقحة من", "reverse_name": "مصدر التنقيح لـ"}}',false) ON CONFLICT(resource_kind,code) DO NOTHING;
INSERT INTO relationship_types(resource_kind,code,forward_name,reverse_name,translations,is_symmetric) VALUES ('record','attached_to','attached to','has attachment','{"ar": {"forward_name": "مرفق بـ", "reverse_name": "له مرفق"}}',false) ON CONFLICT(resource_kind,code) DO NOTHING;
INSERT INTO relationship_types(resource_kind,code,forward_name,reverse_name,translations,is_symmetric) VALUES ('record','responds_to','responds to','has response','{"ar": {"forward_name": "يرد على", "reverse_name": "له رد"}}',false) ON CONFLICT(resource_kind,code) DO NOTHING;
INSERT INTO relationship_types(resource_kind,code,forward_name,reverse_name,translations,is_symmetric) VALUES ('record','references','references','referenced by','{"ar": {"forward_name": "يشير إلى", "reverse_name": "أشار إليه"}}',false) ON CONFLICT(resource_kind,code) DO NOTHING;
INSERT INTO relationship_types(resource_kind,code,forward_name,reverse_name,translations,is_symmetric) VALUES ('record','copy_of','copy of','has copy','{"ar": {"forward_name": "نسخة من", "reverse_name": "له نسخة"}}',false) ON CONFLICT(resource_kind,code) DO NOTHING;
COMMIT;
